export const dataFeeType = [
    {
        id: "1",
        name: 'Service Fee',
        description: 'Ea officia aliqua incididunt adipisicing amet duis qui non qui ad.',
        status: 'Active',
    },
    {
        id: "2",
        name: 'Reissue Fee',
        description: 'Ea officia aliqua incididunt adipisicing amet duis qui non qui ad.',
        status: 'Active',
    },
    {
        id: "3",
        name: 'Cancellation Fee',
        description: 'Ea officia aliqua incididunt adipisicing amet duis qui non qui ad.',
        status: 'Active',
    },
    {
        id: "4",
        name: 'MDR Fee',
        description: 'Ea officia aliqua incididunt adipisicing amet duis qui non qui ad.',
        status: 'Active',
    },
    {
        id: "5",
        name: 'After Office Charge',
        description: 'Ea officia aliqua incididunt adipisicing amet duis qui non qui ad.',
        status: 'Active',
    },
    {
        id: "6",
        name: 'Late Payment',
        description: 'Ea officia aliqua incididunt adipisicing amet duis qui non qui ad.',
        status: 'Active',
    },
    {
        id: "7",
        name: 'Domestic Flight Service Fee',
        description: 'Ea officia aliqua incididunt adipisicing amet duis qui non qui ad.',
        status: 'Active',
    },
    {
        id: "8",
        name: 'International Flight Service Fee',
        description: 'Ea officia aliqua incididunt adipisicing amet duis qui non qui ad.',
        status: 'Active',
    },
    {
        id: "9",
        name: 'Domestic Hotel Service Fee',
        description: 'Ea officia aliqua incididunt adipisicing amet duis qui non qui ad.',
        status: 'Active',
    },
    {
        id: "10",
        name: 'Service Fee',
        description: 'Ea officia aliqua incididunt adipisicing amet duis qui non qui ad.',
        status: 'Active',
    },
    {
        id: "11",
        name: 'Service Fee',
        description: 'Ea officia aliqua incididunt adipisicing amet duis qui non qui ad.',
        status: 'Active',
    },
    {
        id: "12",
        name: 'Service Fee',
        description: 'Ea officia aliqua incididunt adipisicing amet duis qui non qui ad.',
        status: 'Active',
    },
    {
        id: "13",
        name: 'Service Fee',
        description: 'Ea officia aliqua incididunt adipisicing amet duis qui non qui ad.',
        status: 'Active',
    },
    {
        id: "14",
        name: 'Service Fee',
        description: 'Ea officia aliqua incididunt adipisicing amet duis qui non qui ad.',
        status: 'Active',
    },
    {
        id: "15",
        name: 'Service Fee',
        description: 'Ea officia aliqua incididunt adipisicing amet duis qui non qui ad.',
        status: 'Active',
    },
    {
        id: "16",
        name: 'Service Fee',
        description: 'Ea officia aliqua incididunt adipisicing amet duis qui non qui ad.',
        status: 'Active',
    },
    {
        id: "17",
        name: 'Service Fee',
        description: 'Ea officia aliqua incididunt adipisicing amet duis qui non qui ad.',
        status: 'Active',
    },
    {
        id: "18",
        name: 'Service Fee',
        description: 'Ea officia aliqua incididunt adipisicing amet duis qui non qui ad.',
        status: 'Active',
    },
    {
        id: "19",
        name: 'Service Fee',
        description: 'Ea officia aliqua incididunt adipisicing amet duis qui non qui ad.',
        status: 'Active',
    },
    {
        id: "20",
        name: 'Service Fee',
        description: 'Ea officia aliqua incididunt adipisicing amet duis qui non qui ad.',
        status: 'Active',
    }
]